export const constants = {
  ASSESSMENT_WORKFLOW_NAME: 'assessmentWorkFlow_ASSESSMENT_WORKFLOW',
  ASSESSMENT_WORKFLOW: 'assessments',
  INFRASTRUCTURE_WORKFLOW: 'infrastructures',
  INFRASTRUCTURE_WORKFLOW_TYPE: 'INFRASTRUCTURE',
} as const;
