spring:
  application:
    name: parodos-notification-service
    title: Parodos Notification Service
    version: 1.0.18-SNAPSHOT
  jackson:
    default-property-inclusion: non_null
  main:
    lazy-initialization: true
  cloud:
    config:
      enabled: false

  security:
    authentication: ${PARODOS_AUTH:true}

server:
  forward-headers-strategy: framework

springdoc:
  writer-with-order-by-keys: true
  writer-with-default-pretty-printer: true

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus"
