/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.invoker.auth;

import java.net.URI;
import java.util.List;
import java.util.Map;

import com.redhat.parodos.sdk.invoker.ApiException;
import com.redhat.parodos.sdk.invoker.Pair;

public interface Authentication {

	/**
	 * Apply authentication settings to header and query params.
	 * @param queryParams List of query parameters
	 * @param headerParams Map of header parameters
	 * @param cookieParams Map of cookie parameters
	 * @param payload HTTP request body
	 * @param method HTTP method
	 * @param uri URI
	 * @throws ApiException if failed to update the parameters
	 */
	void applyToParams(List<Pair> queryParams, Map<String, String> headerParams, Map<String, String> cookieParams,
			String payload, String method, URI uri) throws ApiException;

}
