/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Provider
 */
@ApiModel(description = "Provider")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1PlanStatusMigrationProvider {

	public static final String SERIALIZED_NAME_DESTINATION = "destination";

	@SerializedName(SERIALIZED_NAME_DESTINATION)
	private V1beta1PlanStatusMigrationMapNetwork destination;

	public static final String SERIALIZED_NAME_SOURCE = "source";

	@SerializedName(SERIALIZED_NAME_SOURCE)
	private V1beta1PlanStatusMigrationMapNetwork source;

	public V1beta1PlanStatusMigrationProvider destination(V1beta1PlanStatusMigrationMapNetwork destination) {

		this.destination = destination;
		return this;
	}

	/**
	 * Get destination
	 * @return destination
	 **/
	@ApiModelProperty(required = true, value = "")

	public V1beta1PlanStatusMigrationMapNetwork getDestination() {
		return destination;
	}

	public void setDestination(V1beta1PlanStatusMigrationMapNetwork destination) {
		this.destination = destination;
	}

	public V1beta1PlanStatusMigrationProvider source(V1beta1PlanStatusMigrationMapNetwork source) {

		this.source = source;
		return this;
	}

	/**
	 * Get source
	 * @return source
	 **/
	@ApiModelProperty(required = true, value = "")

	public V1beta1PlanStatusMigrationMapNetwork getSource() {
		return source;
	}

	public void setSource(V1beta1PlanStatusMigrationMapNetwork source) {
		this.source = source;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1PlanStatusMigrationProvider v1beta1PlanStatusMigrationProvider = (V1beta1PlanStatusMigrationProvider) o;
		return Objects.equals(this.destination, v1beta1PlanStatusMigrationProvider.destination)
				&& Objects.equals(this.source, v1beta1PlanStatusMigrationProvider.source);
	}

	@Override
	public int hashCode() {
		return Objects.hash(destination, source);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1PlanStatusMigrationProvider {\n");
		sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
		sb.append("    source: ").append(toIndentedString(source)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
