/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Precopy durations
 */
@ApiModel(description = "Precopy durations")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1MigrationStatusWarmPrecopies {

	public static final String SERIALIZED_NAME_END = "end";

	@SerializedName(SERIALIZED_NAME_END)
	private OffsetDateTime end;

	public static final String SERIALIZED_NAME_SNAPSHOT = "snapshot";

	@SerializedName(SERIALIZED_NAME_SNAPSHOT)
	private String snapshot;

	public static final String SERIALIZED_NAME_START = "start";

	@SerializedName(SERIALIZED_NAME_START)
	private OffsetDateTime start;

	public V1beta1MigrationStatusWarmPrecopies end(OffsetDateTime end) {

		this.end = end;
		return this;
	}

	/**
	 * Get end
	 * @return end
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public OffsetDateTime getEnd() {
		return end;
	}

	public void setEnd(OffsetDateTime end) {
		this.end = end;
	}

	public V1beta1MigrationStatusWarmPrecopies snapshot(String snapshot) {

		this.snapshot = snapshot;
		return this;
	}

	/**
	 * Get snapshot
	 * @return snapshot
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getSnapshot() {
		return snapshot;
	}

	public void setSnapshot(String snapshot) {
		this.snapshot = snapshot;
	}

	public V1beta1MigrationStatusWarmPrecopies start(OffsetDateTime start) {

		this.start = start;
		return this;
	}

	/**
	 * Get start
	 * @return start
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public OffsetDateTime getStart() {
		return start;
	}

	public void setStart(OffsetDateTime start) {
		this.start = start;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1MigrationStatusWarmPrecopies v1beta1MigrationStatusWarmPrecopies = (V1beta1MigrationStatusWarmPrecopies) o;
		return Objects.equals(this.end, v1beta1MigrationStatusWarmPrecopies.end)
				&& Objects.equals(this.snapshot, v1beta1MigrationStatusWarmPrecopies.snapshot)
				&& Objects.equals(this.start, v1beta1MigrationStatusWarmPrecopies.start);
	}

	@Override
	public int hashCode() {
		return Objects.hash(end, snapshot, start);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1MigrationStatusWarmPrecopies {\n");
		sb.append("    end: ").append(toIndentedString(end)).append("\n");
		sb.append("    snapshot: ").append(toIndentedString(snapshot)).append("\n");
		sb.append("    start: ").append(toIndentedString(start)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
