/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.openapi.models.V1ListMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PlanList is a list of Plan
 */
@ApiModel(description = "PlanList is a list of Plan")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1PlanList implements io.kubernetes.client.common.KubernetesListObject {

	public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";

	@SerializedName(SERIALIZED_NAME_API_VERSION)
	private String apiVersion;

	public static final String SERIALIZED_NAME_ITEMS = "items";

	@SerializedName(SERIALIZED_NAME_ITEMS)
	private List<V1beta1Plan> items = new ArrayList<>();

	public static final String SERIALIZED_NAME_KIND = "kind";

	@SerializedName(SERIALIZED_NAME_KIND)
	private String kind;

	public static final String SERIALIZED_NAME_METADATA = "metadata";

	@SerializedName(SERIALIZED_NAME_METADATA)
	private V1ListMeta metadata = null;

	public V1beta1PlanList apiVersion(String apiVersion) {

		this.apiVersion = apiVersion;
		return this;
	}

	/**
	 * APIVersion defines the versioned schema of this representation of an object.
	 * Servers should convert recognized schemas to the latest internal value, and may
	 * reject unrecognized values. More info:
	 * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	 * @return apiVersion
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(
			value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

	public String getApiVersion() {
		return apiVersion;
	}

	public void setApiVersion(String apiVersion) {
		this.apiVersion = apiVersion;
	}

	public V1beta1PlanList items(List<V1beta1Plan> items) {

		this.items = items;
		return this;
	}

	public V1beta1PlanList addItemsItem(V1beta1Plan itemsItem) {
		this.items.add(itemsItem);
		return this;
	}

	/**
	 * List of plans. More info:
	 * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	 * @return items
	 **/
	@ApiModelProperty(required = true,
			value = "List of plans. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md")

	public List<V1beta1Plan> getItems() {
		return items;
	}

	public void setItems(List<V1beta1Plan> items) {
		this.items = items;
	}

	public V1beta1PlanList kind(String kind) {

		this.kind = kind;
		return this;
	}

	/**
	 * Kind is a string value representing the REST resource this object represents.
	 * Servers may infer this from the endpoint the client submits requests to. Cannot be
	 * updated. In CamelCase. More info:
	 * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	 * @return kind
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(
			value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

	public String getKind() {
		return kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public V1beta1PlanList metadata(V1ListMeta metadata) {

		this.metadata = metadata;
		return this;
	}

	/**
	 * Get metadata
	 * @return metadata
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1ListMeta getMetadata() {
		return metadata;
	}

	public void setMetadata(V1ListMeta metadata) {
		this.metadata = metadata;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1PlanList v1beta1PlanList = (V1beta1PlanList) o;
		return Objects.equals(this.apiVersion, v1beta1PlanList.apiVersion)
				&& Objects.equals(this.items, v1beta1PlanList.items) && Objects.equals(this.kind, v1beta1PlanList.kind)
				&& Objects.equals(this.metadata, v1beta1PlanList.metadata);
	}

	@Override
	public int hashCode() {
		return Objects.hash(apiVersion, items, kind, metadata);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1PlanList {\n");
		sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
		sb.append("    items: ").append(toIndentedString(items)).append("\n");
		sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
		sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
