/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Plan
 */
@ApiModel(description = "Plan")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1PlanStatusMigrationPlan {

	public static final String SERIALIZED_NAME_GENERATION = "generation";

	@SerializedName(SERIALIZED_NAME_GENERATION)
	private Long generation;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_NAMESPACE = "namespace";

	@SerializedName(SERIALIZED_NAME_NAMESPACE)
	private String namespace;

	public static final String SERIALIZED_NAME_UID = "uid";

	@SerializedName(SERIALIZED_NAME_UID)
	private String uid;

	public V1beta1PlanStatusMigrationPlan generation(Long generation) {

		this.generation = generation;
		return this;
	}

	/**
	 * Get generation
	 * @return generation
	 **/
	@ApiModelProperty(required = true, value = "")

	public Long getGeneration() {
		return generation;
	}

	public void setGeneration(Long generation) {
		this.generation = generation;
	}

	public V1beta1PlanStatusMigrationPlan name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * @return name
	 **/
	@ApiModelProperty(required = true, value = "")

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public V1beta1PlanStatusMigrationPlan namespace(String namespace) {

		this.namespace = namespace;
		return this;
	}

	/**
	 * Get namespace
	 * @return namespace
	 **/
	@ApiModelProperty(required = true, value = "")

	public String getNamespace() {
		return namespace;
	}

	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	public V1beta1PlanStatusMigrationPlan uid(String uid) {

		this.uid = uid;
		return this;
	}

	/**
	 * UID is a type that holds unique ID values, including UUIDs. Because we don&#39;t
	 * ONLY use UUIDs, this is an alias to string. Being a type captures intent and helps
	 * make sure that UIDs and names do not get conflated.
	 * @return uid
	 **/
	@ApiModelProperty(required = true,
			value = "UID is a type that holds unique ID values, including UUIDs.  Because we don't ONLY use UUIDs, this is an alias to string.  Being a type captures intent and helps make sure that UIDs and names do not get conflated.")

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1PlanStatusMigrationPlan v1beta1PlanStatusMigrationPlan = (V1beta1PlanStatusMigrationPlan) o;
		return Objects.equals(this.generation, v1beta1PlanStatusMigrationPlan.generation)
				&& Objects.equals(this.name, v1beta1PlanStatusMigrationPlan.name)
				&& Objects.equals(this.namespace, v1beta1PlanStatusMigrationPlan.namespace)
				&& Objects.equals(this.uid, v1beta1PlanStatusMigrationPlan.uid);
	}

	@Override
	public int hashCode() {
		return Objects.hash(generation, name, namespace, uid);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1PlanStatusMigrationPlan {\n");
		sb.append("    generation: ").append(toIndentedString(generation)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
		sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
