/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Pipeline step.
 */
@ApiModel(description = "Pipeline step.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1MigrationStatusPipeline {

	public static final String SERIALIZED_NAME_ANNOTATIONS = "annotations";

	@SerializedName(SERIALIZED_NAME_ANNOTATIONS)
	private Map<String, String> annotations = null;

	public static final String SERIALIZED_NAME_COMPLETED = "completed";

	@SerializedName(SERIALIZED_NAME_COMPLETED)
	private OffsetDateTime completed;

	public static final String SERIALIZED_NAME_DESCRIPTION = "description";

	@SerializedName(SERIALIZED_NAME_DESCRIPTION)
	private String description;

	public static final String SERIALIZED_NAME_ERROR = "error";

	@SerializedName(SERIALIZED_NAME_ERROR)
	private V1beta1MigrationStatusError1 error;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_PHASE = "phase";

	@SerializedName(SERIALIZED_NAME_PHASE)
	private String phase;

	public static final String SERIALIZED_NAME_PROGRESS = "progress";

	@SerializedName(SERIALIZED_NAME_PROGRESS)
	private V1beta1MigrationStatusProgress progress;

	public static final String SERIALIZED_NAME_REASON = "reason";

	@SerializedName(SERIALIZED_NAME_REASON)
	private String reason;

	public static final String SERIALIZED_NAME_STARTED = "started";

	@SerializedName(SERIALIZED_NAME_STARTED)
	private OffsetDateTime started;

	public static final String SERIALIZED_NAME_TASKS = "tasks";

	@SerializedName(SERIALIZED_NAME_TASKS)
	private List<V1beta1MigrationStatusTasks> tasks = null;

	public V1beta1MigrationStatusPipeline annotations(Map<String, String> annotations) {

		this.annotations = annotations;
		return this;
	}

	public V1beta1MigrationStatusPipeline putAnnotationsItem(String key, String annotationsItem) {
		if (this.annotations == null) {
			this.annotations = new HashMap<>();
		}
		this.annotations.put(key, annotationsItem);
		return this;
	}

	/**
	 * Annotations.
	 * @return annotations
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Annotations.")

	public Map<String, String> getAnnotations() {
		return annotations;
	}

	public void setAnnotations(Map<String, String> annotations) {
		this.annotations = annotations;
	}

	public V1beta1MigrationStatusPipeline completed(OffsetDateTime completed) {

		this.completed = completed;
		return this;
	}

	/**
	 * Completed timestamp.
	 * @return completed
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Completed timestamp.")

	public OffsetDateTime getCompleted() {
		return completed;
	}

	public void setCompleted(OffsetDateTime completed) {
		this.completed = completed;
	}

	public V1beta1MigrationStatusPipeline description(String description) {

		this.description = description;
		return this;
	}

	/**
	 * Name
	 * @return description
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Name")

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public V1beta1MigrationStatusPipeline error(V1beta1MigrationStatusError1 error) {

		this.error = error;
		return this;
	}

	/**
	 * Get error
	 * @return error
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1beta1MigrationStatusError1 getError() {
		return error;
	}

	public void setError(V1beta1MigrationStatusError1 error) {
		this.error = error;
	}

	public V1beta1MigrationStatusPipeline name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Name.
	 * @return name
	 **/
	@ApiModelProperty(required = true, value = "Name.")

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public V1beta1MigrationStatusPipeline phase(String phase) {

		this.phase = phase;
		return this;
	}

	/**
	 * Phase
	 * @return phase
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Phase")

	public String getPhase() {
		return phase;
	}

	public void setPhase(String phase) {
		this.phase = phase;
	}

	public V1beta1MigrationStatusPipeline progress(V1beta1MigrationStatusProgress progress) {

		this.progress = progress;
		return this;
	}

	/**
	 * Get progress
	 * @return progress
	 **/
	@ApiModelProperty(required = true, value = "")

	public V1beta1MigrationStatusProgress getProgress() {
		return progress;
	}

	public void setProgress(V1beta1MigrationStatusProgress progress) {
		this.progress = progress;
	}

	public V1beta1MigrationStatusPipeline reason(String reason) {

		this.reason = reason;
		return this;
	}

	/**
	 * Reason
	 * @return reason
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Reason")

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public V1beta1MigrationStatusPipeline started(OffsetDateTime started) {

		this.started = started;
		return this;
	}

	/**
	 * Started timestamp.
	 * @return started
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Started timestamp.")

	public OffsetDateTime getStarted() {
		return started;
	}

	public void setStarted(OffsetDateTime started) {
		this.started = started;
	}

	public V1beta1MigrationStatusPipeline tasks(List<V1beta1MigrationStatusTasks> tasks) {

		this.tasks = tasks;
		return this;
	}

	public V1beta1MigrationStatusPipeline addTasksItem(V1beta1MigrationStatusTasks tasksItem) {
		if (this.tasks == null) {
			this.tasks = new ArrayList<>();
		}
		this.tasks.add(tasksItem);
		return this;
	}

	/**
	 * Nested tasks.
	 * @return tasks
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Nested tasks.")

	public List<V1beta1MigrationStatusTasks> getTasks() {
		return tasks;
	}

	public void setTasks(List<V1beta1MigrationStatusTasks> tasks) {
		this.tasks = tasks;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1MigrationStatusPipeline v1beta1MigrationStatusPipeline = (V1beta1MigrationStatusPipeline) o;
		return Objects.equals(this.annotations, v1beta1MigrationStatusPipeline.annotations)
				&& Objects.equals(this.completed, v1beta1MigrationStatusPipeline.completed)
				&& Objects.equals(this.description, v1beta1MigrationStatusPipeline.description)
				&& Objects.equals(this.error, v1beta1MigrationStatusPipeline.error)
				&& Objects.equals(this.name, v1beta1MigrationStatusPipeline.name)
				&& Objects.equals(this.phase, v1beta1MigrationStatusPipeline.phase)
				&& Objects.equals(this.progress, v1beta1MigrationStatusPipeline.progress)
				&& Objects.equals(this.reason, v1beta1MigrationStatusPipeline.reason)
				&& Objects.equals(this.started, v1beta1MigrationStatusPipeline.started)
				&& Objects.equals(this.tasks, v1beta1MigrationStatusPipeline.tasks);
	}

	@Override
	public int hashCode() {
		return Objects.hash(annotations, completed, description, error, name, phase, progress, reason, started, tasks);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1MigrationStatusPipeline {\n");
		sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
		sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    error: ").append(toIndentedString(error)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
		sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
		sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
		sb.append("    started: ").append(toIndentedString(started)).append("\n");
		sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
