/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Warm migration status
 */
@ApiModel(description = "Warm migration status")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1MigrationStatusWarm {

	public static final String SERIALIZED_NAME_CONSECUTIVE_FAILURES = "consecutiveFailures";

	@SerializedName(SERIALIZED_NAME_CONSECUTIVE_FAILURES)
	private Integer consecutiveFailures;

	public static final String SERIALIZED_NAME_FAILURES = "failures";

	@SerializedName(SERIALIZED_NAME_FAILURES)
	private Integer failures;

	public static final String SERIALIZED_NAME_NEXT_PRECOPY_AT = "nextPrecopyAt";

	@SerializedName(SERIALIZED_NAME_NEXT_PRECOPY_AT)
	private OffsetDateTime nextPrecopyAt;

	public static final String SERIALIZED_NAME_PRECOPIES = "precopies";

	@SerializedName(SERIALIZED_NAME_PRECOPIES)
	private List<V1beta1MigrationStatusWarmPrecopies> precopies = null;

	public static final String SERIALIZED_NAME_SUCCESSES = "successes";

	@SerializedName(SERIALIZED_NAME_SUCCESSES)
	private Integer successes;

	public V1beta1MigrationStatusWarm consecutiveFailures(Integer consecutiveFailures) {

		this.consecutiveFailures = consecutiveFailures;
		return this;
	}

	/**
	 * Get consecutiveFailures
	 * @return consecutiveFailures
	 **/
	@ApiModelProperty(required = true, value = "")

	public Integer getConsecutiveFailures() {
		return consecutiveFailures;
	}

	public void setConsecutiveFailures(Integer consecutiveFailures) {
		this.consecutiveFailures = consecutiveFailures;
	}

	public V1beta1MigrationStatusWarm failures(Integer failures) {

		this.failures = failures;
		return this;
	}

	/**
	 * Get failures
	 * @return failures
	 **/
	@ApiModelProperty(required = true, value = "")

	public Integer getFailures() {
		return failures;
	}

	public void setFailures(Integer failures) {
		this.failures = failures;
	}

	public V1beta1MigrationStatusWarm nextPrecopyAt(OffsetDateTime nextPrecopyAt) {

		this.nextPrecopyAt = nextPrecopyAt;
		return this;
	}

	/**
	 * Get nextPrecopyAt
	 * @return nextPrecopyAt
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public OffsetDateTime getNextPrecopyAt() {
		return nextPrecopyAt;
	}

	public void setNextPrecopyAt(OffsetDateTime nextPrecopyAt) {
		this.nextPrecopyAt = nextPrecopyAt;
	}

	public V1beta1MigrationStatusWarm precopies(List<V1beta1MigrationStatusWarmPrecopies> precopies) {

		this.precopies = precopies;
		return this;
	}

	public V1beta1MigrationStatusWarm addPrecopiesItem(V1beta1MigrationStatusWarmPrecopies precopiesItem) {
		if (this.precopies == null) {
			this.precopies = new ArrayList<>();
		}
		this.precopies.add(precopiesItem);
		return this;
	}

	/**
	 * Get precopies
	 * @return precopies
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1beta1MigrationStatusWarmPrecopies> getPrecopies() {
		return precopies;
	}

	public void setPrecopies(List<V1beta1MigrationStatusWarmPrecopies> precopies) {
		this.precopies = precopies;
	}

	public V1beta1MigrationStatusWarm successes(Integer successes) {

		this.successes = successes;
		return this;
	}

	/**
	 * Get successes
	 * @return successes
	 **/
	@ApiModelProperty(required = true, value = "")

	public Integer getSuccesses() {
		return successes;
	}

	public void setSuccesses(Integer successes) {
		this.successes = successes;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1MigrationStatusWarm v1beta1MigrationStatusWarm = (V1beta1MigrationStatusWarm) o;
		return Objects.equals(this.consecutiveFailures, v1beta1MigrationStatusWarm.consecutiveFailures)
				&& Objects.equals(this.failures, v1beta1MigrationStatusWarm.failures)
				&& Objects.equals(this.nextPrecopyAt, v1beta1MigrationStatusWarm.nextPrecopyAt)
				&& Objects.equals(this.precopies, v1beta1MigrationStatusWarm.precopies)
				&& Objects.equals(this.successes, v1beta1MigrationStatusWarm.successes);
	}

	@Override
	public int hashCode() {
		return Objects.hash(consecutiveFailures, failures, nextPrecopyAt, precopies, successes);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1MigrationStatusWarm {\n");
		sb.append("    consecutiveFailures: ").append(toIndentedString(consecutiveFailures)).append("\n");
		sb.append("    failures: ").append(toIndentedString(failures)).append("\n");
		sb.append("    nextPrecopyAt: ").append(toIndentedString(nextPrecopyAt)).append("\n");
		sb.append("    precopies: ").append(toIndentedString(precopies)).append("\n");
		sb.append("    successes: ").append(toIndentedString(successes)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
