/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Progress.
 */
@ApiModel(description = "Progress.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1MigrationStatusProgress {

	public static final String SERIALIZED_NAME_COMPLETED = "completed";

	@SerializedName(SERIALIZED_NAME_COMPLETED)
	private Long completed;

	public static final String SERIALIZED_NAME_TOTAL = "total";

	@SerializedName(SERIALIZED_NAME_TOTAL)
	private Long total;

	public V1beta1MigrationStatusProgress completed(Long completed) {

		this.completed = completed;
		return this;
	}

	/**
	 * Completed units.
	 * @return completed
	 **/
	@ApiModelProperty(required = true, value = "Completed units.")

	public Long getCompleted() {
		return completed;
	}

	public void setCompleted(Long completed) {
		this.completed = completed;
	}

	public V1beta1MigrationStatusProgress total(Long total) {

		this.total = total;
		return this;
	}

	/**
	 * Total units.
	 * @return total
	 **/
	@ApiModelProperty(required = true, value = "Total units.")

	public Long getTotal() {
		return total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1MigrationStatusProgress v1beta1MigrationStatusProgress = (V1beta1MigrationStatusProgress) o;
		return Objects.equals(this.completed, v1beta1MigrationStatusProgress.completed)
				&& Objects.equals(this.total, v1beta1MigrationStatusProgress.total);
	}

	@Override
	public int hashCode() {
		return Objects.hash(completed, total);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1MigrationStatusProgress {\n");
		sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
		sb.append("    total: ").append(toIndentedString(total)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
