/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Migration
 */
@ApiModel(description = "Migration")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1PlanStatusMigration {

	public static final String SERIALIZED_NAME_COMPLETED = "completed";

	@SerializedName(SERIALIZED_NAME_COMPLETED)
	private OffsetDateTime completed;

	public static final String SERIALIZED_NAME_HISTORY = "history";

	@SerializedName(SERIALIZED_NAME_HISTORY)
	private List<V1beta1PlanStatusMigrationHistory> history = null;

	public static final String SERIALIZED_NAME_STARTED = "started";

	@SerializedName(SERIALIZED_NAME_STARTED)
	private OffsetDateTime started;

	public static final String SERIALIZED_NAME_VMS = "vms";

	@SerializedName(SERIALIZED_NAME_VMS)
	private List<V1beta1MigrationStatusVms> vms = null;

	public V1beta1PlanStatusMigration completed(OffsetDateTime completed) {

		this.completed = completed;
		return this;
	}

	/**
	 * Completed timestamp.
	 * @return completed
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Completed timestamp.")

	public OffsetDateTime getCompleted() {
		return completed;
	}

	public void setCompleted(OffsetDateTime completed) {
		this.completed = completed;
	}

	public V1beta1PlanStatusMigration history(List<V1beta1PlanStatusMigrationHistory> history) {

		this.history = history;
		return this;
	}

	public V1beta1PlanStatusMigration addHistoryItem(V1beta1PlanStatusMigrationHistory historyItem) {
		if (this.history == null) {
			this.history = new ArrayList<>();
		}
		this.history.add(historyItem);
		return this;
	}

	/**
	 * History
	 * @return history
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "History")

	public List<V1beta1PlanStatusMigrationHistory> getHistory() {
		return history;
	}

	public void setHistory(List<V1beta1PlanStatusMigrationHistory> history) {
		this.history = history;
	}

	public V1beta1PlanStatusMigration started(OffsetDateTime started) {

		this.started = started;
		return this;
	}

	/**
	 * Started timestamp.
	 * @return started
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "Started timestamp.")

	public OffsetDateTime getStarted() {
		return started;
	}

	public void setStarted(OffsetDateTime started) {
		this.started = started;
	}

	public V1beta1PlanStatusMigration vms(List<V1beta1MigrationStatusVms> vms) {

		this.vms = vms;
		return this;
	}

	public V1beta1PlanStatusMigration addVmsItem(V1beta1MigrationStatusVms vmsItem) {
		if (this.vms == null) {
			this.vms = new ArrayList<>();
		}
		this.vms.add(vmsItem);
		return this;
	}

	/**
	 * VM status
	 * @return vms
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "VM status")

	public List<V1beta1MigrationStatusVms> getVms() {
		return vms;
	}

	public void setVms(List<V1beta1MigrationStatusVms> vms) {
		this.vms = vms;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1PlanStatusMigration v1beta1PlanStatusMigration = (V1beta1PlanStatusMigration) o;
		return Objects.equals(this.completed, v1beta1PlanStatusMigration.completed)
				&& Objects.equals(this.history, v1beta1PlanStatusMigration.history)
				&& Objects.equals(this.started, v1beta1PlanStatusMigration.started)
				&& Objects.equals(this.vms, v1beta1PlanStatusMigration.vms);
	}

	@Override
	public int hashCode() {
		return Objects.hash(completed, history, started, vms);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1PlanStatusMigration {\n");
		sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
		sb.append("    history: ").append(toIndentedString(history)).append("\n");
		sb.append("    started: ").append(toIndentedString(started)).append("\n");
		sb.append("    vms: ").append(toIndentedString(vms)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
