/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.examples.vmmigration.dto.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PlanStatus defines the observed state of Plan.
 */
@ApiModel(description = "PlanStatus defines the observed state of Plan.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-17T23:50:06.262Z[Etc/UTC]")
public class V1beta1PlanStatus {

	public static final String SERIALIZED_NAME_CONDITIONS = "conditions";

	@SerializedName(SERIALIZED_NAME_CONDITIONS)
	private List<V1beta1MigrationStatusConditions> conditions = null;

	public static final String SERIALIZED_NAME_MIGRATION = "migration";

	@SerializedName(SERIALIZED_NAME_MIGRATION)
	private V1beta1PlanStatusMigration migration;

	public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";

	@SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
	private Long observedGeneration;

	public V1beta1PlanStatus conditions(List<V1beta1MigrationStatusConditions> conditions) {

		this.conditions = conditions;
		return this;
	}

	public V1beta1PlanStatus addConditionsItem(V1beta1MigrationStatusConditions conditionsItem) {
		if (this.conditions == null) {
			this.conditions = new ArrayList<>();
		}
		this.conditions.add(conditionsItem);
		return this;
	}

	/**
	 * List of conditions.
	 * @return conditions
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "List of conditions.")

	public List<V1beta1MigrationStatusConditions> getConditions() {
		return conditions;
	}

	public void setConditions(List<V1beta1MigrationStatusConditions> conditions) {
		this.conditions = conditions;
	}

	public V1beta1PlanStatus migration(V1beta1PlanStatusMigration migration) {

		this.migration = migration;
		return this;
	}

	/**
	 * Get migration
	 * @return migration
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1beta1PlanStatusMigration getMigration() {
		return migration;
	}

	public void setMigration(V1beta1PlanStatusMigration migration) {
		this.migration = migration;
	}

	public V1beta1PlanStatus observedGeneration(Long observedGeneration) {

		this.observedGeneration = observedGeneration;
		return this;
	}

	/**
	 * The most recent generation observed by the controller.
	 * @return observedGeneration
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "The most recent generation observed by the controller.")

	public Long getObservedGeneration() {
		return observedGeneration;
	}

	public void setObservedGeneration(Long observedGeneration) {
		this.observedGeneration = observedGeneration;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1beta1PlanStatus v1beta1PlanStatus = (V1beta1PlanStatus) o;
		return Objects.equals(this.conditions, v1beta1PlanStatus.conditions)
				&& Objects.equals(this.migration, v1beta1PlanStatus.migration)
				&& Objects.equals(this.observedGeneration, v1beta1PlanStatus.observedGeneration);
	}

	@Override
	public int hashCode() {
		return Objects.hash(conditions, migration, observedGeneration);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1beta1PlanStatus {\n");
		sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
		sb.append("    migration: ").append(toIndentedString(migration)).append("\n");
		sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
