/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.invoker;

import java.util.List;
import java.util.Map;

/**
 * API response returned by API call.
 */
public class ApiResponse<T> {

	final private int statusCode;

	final private Map<String, List<String>> headers;

	final private T data;

	/**
	 * <p>
	 * Constructor for ApiResponse.
	 * </p>
	 * @param statusCode The status code of HTTP response
	 * @param headers The headers of HTTP response
	 */
	public ApiResponse(int statusCode, Map<String, List<String>> headers) {
		this(statusCode, headers, null);
	}

	/**
	 * <p>
	 * Constructor for ApiResponse.
	 * </p>
	 * @param statusCode The status code of HTTP response
	 * @param headers The headers of HTTP response
	 * @param data The object deserialized from response bod
	 */
	public ApiResponse(int statusCode, Map<String, List<String>> headers, T data) {
		this.statusCode = statusCode;
		this.headers = headers;
		this.data = data;
	}

	/**
	 * <p>
	 * Get the <code>status code</code>.
	 * </p>
	 * @return the status code
	 */
	public int getStatusCode() {
		return statusCode;
	}

	/**
	 * <p>
	 * Get the <code>headers</code>.
	 * </p>
	 * @return a {@link java.util.Map} of headers
	 */
	public Map<String, List<String>> getHeaders() {
		return headers;
	}

	/**
	 * <p>
	 * Get the <code>data</code>.
	 * </p>
	 * @return the data
	 */
	public T getData() {
		return data;
	}

}
