/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.invoker;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Pair {

	private String name = "";

	private String value = "";

	public Pair(String name, String value) {
		setName(name);
		setValue(value);
	}

	private void setName(String name) {
		if (!isValidString(name)) {
			return;
		}

		this.name = name;
	}

	private void setValue(String value) {
		if (!isValidString(value)) {
			return;
		}

		this.value = value;
	}

	public String getName() {
		return this.name;
	}

	public String getValue() {
		return this.value;
	}

	private boolean isValidString(String arg) {
		if (arg == null) {
			return false;
		}

		return true;
	}

}
