logging:
  level:
    ROOT: INFO
    com.redhat.parodos: DEBUG
spring:
  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389
    connection:
      userDNPatterns: "uid={0},ou=people"
      groupSearchBase: "ou=groups"
      url: "ldap://ldap:389/dc=parodos,dc=dev"
      passwordAttribute: "userPassword"
      managerDN: "cn=admin,dc=parodos,dc=dev"
      managerPassword: "admin"
  lifecycle:
    timeout-per-shutdown-phase: "25s"

notification:
  url: "${NOTIFICATION_SERVER_URL:http://localhost:8081}"
  auth:
    basic:
      user: test
      password: test

workflows:
  mta:
    url: "${MTA_URL:https://mta-openshift-mta.apps.parodos-dev.projects.ecosystem.sysdeseng.com}"
