/*
 * Parodos Notification Service API
 * This is the API documentation for the Parodos Notification Service. It provides operations to send out and check notification. The endpoints are secured with oAuth2/OpenID and cannot be accessed without a valid token.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.notification.sdk.model;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.parodos.notification.sdk.api.JSON;

/**
 * NotificationRecordResponseDTO
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class NotificationRecordResponseDTO {

	public static final String SERIALIZED_NAME_BODY = "body";

	@SerializedName(SERIALIZED_NAME_BODY)
	private String body;

	public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";

	@SerializedName(SERIALIZED_NAME_CREATED_ON)
	private Date createdOn;

	public static final String SERIALIZED_NAME_FOLDER = "folder";

	@SerializedName(SERIALIZED_NAME_FOLDER)
	private String folder;

	public static final String SERIALIZED_NAME_FROMUSER = "fromuser";

	@SerializedName(SERIALIZED_NAME_FROMUSER)
	private String fromuser;

	public static final String SERIALIZED_NAME_ID = "id";

	@SerializedName(SERIALIZED_NAME_ID)
	private UUID id;

	public static final String SERIALIZED_NAME_MESSAGE_TYPE = "messageType";

	@SerializedName(SERIALIZED_NAME_MESSAGE_TYPE)
	private String messageType;

	public static final String SERIALIZED_NAME_READ = "read";

	@SerializedName(SERIALIZED_NAME_READ)
	private Boolean read;

	public static final String SERIALIZED_NAME_SUBJECT = "subject";

	@SerializedName(SERIALIZED_NAME_SUBJECT)
	private String subject;

	public static final String SERIALIZED_NAME_TAGS = "tags";

	@SerializedName(SERIALIZED_NAME_TAGS)
	private List<String> tags;

	public NotificationRecordResponseDTO() {
	}

	public NotificationRecordResponseDTO body(String body) {

		this.body = body;
		return this;
	}

	/**
	 * Get body
	 * @return body
	 **/
	@jakarta.annotation.Nullable
	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public NotificationRecordResponseDTO createdOn(Date createdOn) {

		this.createdOn = createdOn;
		return this;
	}

	/**
	 * Get createdOn
	 * @return createdOn
	 **/
	@jakarta.annotation.Nullable
	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public NotificationRecordResponseDTO folder(String folder) {

		this.folder = folder;
		return this;
	}

	/**
	 * Get folder
	 * @return folder
	 **/
	@jakarta.annotation.Nullable
	public String getFolder() {
		return folder;
	}

	public void setFolder(String folder) {
		this.folder = folder;
	}

	public NotificationRecordResponseDTO fromuser(String fromuser) {

		this.fromuser = fromuser;
		return this;
	}

	/**
	 * Get fromuser
	 * @return fromuser
	 **/
	@jakarta.annotation.Nullable
	public String getFromuser() {
		return fromuser;
	}

	public void setFromuser(String fromuser) {
		this.fromuser = fromuser;
	}

	public NotificationRecordResponseDTO id(UUID id) {

		this.id = id;
		return this;
	}

	/**
	 * Get id
	 * @return id
	 **/
	@jakarta.annotation.Nullable
	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public NotificationRecordResponseDTO messageType(String messageType) {

		this.messageType = messageType;
		return this;
	}

	/**
	 * Get messageType
	 * @return messageType
	 **/
	@jakarta.annotation.Nullable
	public String getMessageType() {
		return messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public NotificationRecordResponseDTO read(Boolean read) {

		this.read = read;
		return this;
	}

	/**
	 * Get read
	 * @return read
	 **/
	@jakarta.annotation.Nullable
	public Boolean getRead() {
		return read;
	}

	public void setRead(Boolean read) {
		this.read = read;
	}

	public NotificationRecordResponseDTO subject(String subject) {

		this.subject = subject;
		return this;
	}

	/**
	 * Get subject
	 * @return subject
	 **/
	@jakarta.annotation.Nullable
	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public NotificationRecordResponseDTO tags(List<String> tags) {

		this.tags = tags;
		return this;
	}

	public NotificationRecordResponseDTO addTagsItem(String tagsItem) {
		if (this.tags == null) {
			this.tags = new ArrayList<>();
		}
		this.tags.add(tagsItem);
		return this;
	}

	/**
	 * Get tags
	 * @return tags
	 **/
	@jakarta.annotation.Nullable
	public List<String> getTags() {
		return tags;
	}

	public void setTags(List<String> tags) {
		this.tags = tags;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		NotificationRecordResponseDTO notificationRecordResponseDTO = (NotificationRecordResponseDTO) o;
		return Objects.equals(this.body, notificationRecordResponseDTO.body)
				&& Objects.equals(this.createdOn, notificationRecordResponseDTO.createdOn)
				&& Objects.equals(this.folder, notificationRecordResponseDTO.folder)
				&& Objects.equals(this.fromuser, notificationRecordResponseDTO.fromuser)
				&& Objects.equals(this.id, notificationRecordResponseDTO.id)
				&& Objects.equals(this.messageType, notificationRecordResponseDTO.messageType)
				&& Objects.equals(this.read, notificationRecordResponseDTO.read)
				&& Objects.equals(this.subject, notificationRecordResponseDTO.subject)
				&& Objects.equals(this.tags, notificationRecordResponseDTO.tags);
	}

	@Override
	public int hashCode() {
		return Objects.hash(body, createdOn, folder, fromuser, id, messageType, read, subject, tags);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class NotificationRecordResponseDTO {\n");
		sb.append("    body: ").append(toIndentedString(body)).append("\n");
		sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
		sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
		sb.append("    fromuser: ").append(toIndentedString(fromuser)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
		sb.append("    read: ").append(toIndentedString(read)).append("\n");
		sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
		sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;

	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>();
		openapiFields.add("body");
		openapiFields.add("createdOn");
		openapiFields.add("folder");
		openapiFields.add("fromuser");
		openapiFields.add("id");
		openapiFields.add("messageType");
		openapiFields.add("read");
		openapiFields.add("subject");
		openapiFields.add("tags");

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>();
	}

	/**
	 * Validates the JSON Object and throws an exception if issues found
	 * @param jsonObj JSON Object
	 * @throws IOException if the JSON Object is invalid with respect to
	 * NotificationRecordResponseDTO
	 */
	public static void validateJsonObject(JsonObject jsonObj) throws IOException {
		if (jsonObj == null) {
			if (!NotificationRecordResponseDTO.openapiRequiredFields.isEmpty()) { // has
																					// required
																					// fields
																					// but
																					// JSON
																					// object
																					// is
																					// null
				throw new IllegalArgumentException(String.format(
						"The required field(s) %s in NotificationRecordResponseDTO is not found in the empty JSON string",
						NotificationRecordResponseDTO.openapiRequiredFields.toString()));
			}
		}

		Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
		// check to see if the JSON string contains additional fields
		for (Entry<String, JsonElement> entry : entries) {
			if (!NotificationRecordResponseDTO.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(String.format(
						"The field `%s` in the JSON string is not defined in the `NotificationRecordResponseDTO` properties. JSON: %s",
						entry.getKey(), jsonObj.toString()));
			}
		}
		if ((jsonObj.get("body") != null && !jsonObj.get("body").isJsonNull())
				&& !jsonObj.get("body").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format("Expected the field `body` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("body").toString()));
		}
		if ((jsonObj.get("folder") != null && !jsonObj.get("folder").isJsonNull())
				&& !jsonObj.get("folder").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format("Expected the field `folder` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("folder").toString()));
		}
		if ((jsonObj.get("fromuser") != null && !jsonObj.get("fromuser").isJsonNull())
				&& !jsonObj.get("fromuser").isJsonPrimitive()) {
			throw new IllegalArgumentException(String.format(
					"Expected the field `fromuser` to be a primitive type in the JSON string but got `%s`",
					jsonObj.get("fromuser").toString()));
		}
		if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("id").toString()));
		}
		if ((jsonObj.get("messageType") != null && !jsonObj.get("messageType").isJsonNull())
				&& !jsonObj.get("messageType").isJsonPrimitive()) {
			throw new IllegalArgumentException(String.format(
					"Expected the field `messageType` to be a primitive type in the JSON string but got `%s`",
					jsonObj.get("messageType").toString()));
		}
		if ((jsonObj.get("subject") != null && !jsonObj.get("subject").isJsonNull())
				&& !jsonObj.get("subject").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format("Expected the field `subject` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("subject").toString()));
		}
		// ensure the optional json data is an array if present
		if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonArray()) {
			throw new IllegalArgumentException(
					String.format("Expected the field `tags` to be an array in the JSON string but got `%s`",
							jsonObj.get("tags").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!NotificationRecordResponseDTO.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'NotificationRecordResponseDTO'
								// and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<NotificationRecordResponseDTO> thisAdapter = gson.getDelegateAdapter(this,
					TypeToken.get(NotificationRecordResponseDTO.class));

			return (TypeAdapter<T>) new TypeAdapter<NotificationRecordResponseDTO>() {
				@Override
				public void write(JsonWriter out, NotificationRecordResponseDTO value) throws IOException {
					JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
					elementAdapter.write(out, obj);
				}

				@Override
				public NotificationRecordResponseDTO read(JsonReader in) throws IOException {
					JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
					validateJsonObject(jsonObj);
					return thisAdapter.fromJsonTree(jsonObj);
				}

			}.nullSafe();
		}

	}

	/**
	 * Create an instance of NotificationRecordResponseDTO given an JSON string
	 * @param jsonString JSON string
	 * @return An instance of NotificationRecordResponseDTO
	 * @throws IOException if the JSON string is invalid with respect to
	 * NotificationRecordResponseDTO
	 */
	public static NotificationRecordResponseDTO fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, NotificationRecordResponseDTO.class);
	}

	/**
	 * Convert an instance of NotificationRecordResponseDTO to an JSON string
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}

}
