/*
 * Parodos Notification Service API
 * This is the API documentation for the Parodos Notification Service. It provides operations to send out and check notification. The endpoints are secured with oAuth2/OpenID and cannot be accessed without a valid token.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.notification.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Pageable
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Pageable {

	public static final String SERIALIZED_NAME_PAGE = "page";

	@SerializedName(SERIALIZED_NAME_PAGE)
	private Integer page;

	public static final String SERIALIZED_NAME_SIZE = "size";

	@SerializedName(SERIALIZED_NAME_SIZE)
	private Integer size;

	public static final String SERIALIZED_NAME_SORT = "sort";

	@SerializedName(SERIALIZED_NAME_SORT)
	private List<String> sort = null;

	public Pageable() {
	}

	public Pageable page(Integer page) {

		this.page = page;
		return this;
	}

	/**
	 * Get page minimum: 0
	 * @return page
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getPage() {
		return page;
	}

	public void setPage(Integer page) {
		this.page = page;
	}

	public Pageable size(Integer size) {

		this.size = size;
		return this;
	}

	/**
	 * Get size minimum: 1
	 * @return size
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getSize() {
		return size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public Pageable sort(List<String> sort) {

		this.sort = sort;
		return this;
	}

	public Pageable addSortItem(String sortItem) {
		if (this.sort == null) {
			this.sort = new ArrayList<String>();
		}
		this.sort.add(sortItem);
		return this;
	}

	/**
	 * Get sort
	 * @return sort
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<String> getSort() {
		return sort;
	}

	public void setSort(List<String> sort) {
		this.sort = sort;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Pageable pageable = (Pageable) o;
		return Objects.equals(this.page, pageable.page) && Objects.equals(this.size, pageable.size)
				&& Objects.equals(this.sort, pageable.sort);
	}

	@Override
	public int hashCode() {
		return Objects.hash(page, size, sort);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Pageable {\n");
		sb.append("    page: ").append(toIndentedString(page)).append("\n");
		sb.append("    size: ").append(toIndentedString(size)).append("\n");
		sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
