/*
 * Parodos Notification Service API
 * This is the API documentation for the Parodos Notification Service. It provides operations to send out and check notification. The endpoints are secured with oAuth2/OpenID and cannot be accessed without a valid token.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.notification.sdk.api;

import com.redhat.parodos.notification.sdk.api.ApiException;
import com.redhat.parodos.notification.sdk.model.NotificationRecordResponseDTO;
import com.redhat.parodos.notification.sdk.model.Pageable;
import com.redhat.parodos.notification.sdk.model.PagedModelNotificationRecordResponseDTO;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificationRecordApi
 */
@Ignore
public class NotificationRecordApiTest {

	private final NotificationRecordApi api = new NotificationRecordApi();

	/**
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void countUnreadNotificationsTest() throws ApiException {
		String state = null;
		Integer response = api.countUnreadNotifications(state);
		// TODO: test validations
	}

	/**
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void deleteNotificationTest() throws ApiException {
		UUID id = null;
		api.deleteNotification(id);
		// TODO: test validations
	}

	/**
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void getNotificationsTest() throws ApiException {
		Pageable pageable = null;
		String state = null;
		String searchTerm = null;
		PagedModelNotificationRecordResponseDTO response = api.getNotifications(pageable, state, searchTerm);
		// TODO: test validations
	}

	/**
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void updateNotificationStatusByIdTest() throws ApiException {
		UUID id = null;
		String operation = null;
		NotificationRecordResponseDTO response = api.updateNotificationStatusById(id, operation);
		// TODO: test validations
	}

}
