/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.model;

import org.junit.Test;

/**
 * Model tests for ProjectResponseDTO
 */
public class ProjectResponseDTOTest {

	private final ProjectResponseDTO model = new ProjectResponseDTO();

	/**
	 * Model tests for ProjectResponseDTO
	 */
	@Test
	public void testProjectResponseDTO() {
		// TODO: test ProjectResponseDTO
	}

	/**
	 * Test the property 'createDate'
	 */
	@Test
	public void createDateTest() {
		// TODO: test createDate
	}

	/**
	 * Test the property 'description'
	 */
	@Test
	public void descriptionTest() {
		// TODO: test description
	}

	/**
	 * Test the property 'id'
	 */
	@Test
	public void idTest() {
		// TODO: test id
	}

	/**
	 * Test the property 'modifyDate'
	 */
	@Test
	public void modifyDateTest() {
		// TODO: test modifyDate
	}

	/**
	 * Test the property 'name'
	 */
	@Test
	public void nameTest() {
		// TODO: test name
	}

	/**
	 * Test the property 'status'
	 */
	@Test
	public void statusTest() {
		// TODO: test status
	}

	/**
	 * Test the property 'username'
	 */
	@Test
	public void usernameTest() {
		// TODO: test username
	}

}
