/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.parodos.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.parodos.sdk.model.WorkFlowOption;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkFlowOptions
 */
public class WorkFlowOptionsTest {
    private final WorkFlowOptions model = new WorkFlowOptions();

    /**
     * Model tests for WorkFlowOptions
     */
    @Test
    public void testWorkFlowOptions() {
        // TODO: test WorkFlowOptions
    }

    /**
     * Test the property 'currentVersion'
     */
    @Test
    public void currentVersionTest() {
        // TODO: test currentVersion
    }

    /**
     * Test the property 'upgradeOptions'
     */
    @Test
    public void upgradeOptionsTest() {
        // TODO: test upgradeOptions
    }

    /**
     * Test the property 'migrationOptions'
     */
    @Test
    public void migrationOptionsTest() {
        // TODO: test migrationOptions
    }

    /**
     * Test the property 'newOptions'
     */
    @Test
    public void newOptionsTest() {
        // TODO: test newOptions
    }

    /**
     * Test the property 'continuationOptions'
     */
    @Test
    public void continuationOptionsTest() {
        // TODO: test continuationOptions
    }

    /**
     * Test the property 'otherOptions'
     */
    @Test
    public void otherOptionsTest() {
        // TODO: test otherOptions
    }

    /**
     * Test the property 'optionsAvailable'
     */
    @Test
    public void optionsAvailableTest() {
        // TODO: test optionsAvailable
    }

}
