/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.model;

import org.junit.Test;

/**
 * Model tests for WorkFlowContextResponseDTO
 */
public class WorkFlowContextResponseDTOTest {

	private final WorkFlowContextResponseDTO model = new WorkFlowContextResponseDTO();

	/**
	 * Model tests for WorkFlowContextResponseDTO
	 */
	@Test
	public void testWorkFlowContextResponseDTO() {
		// TODO: test WorkFlowContextResponseDTO
	}

	/**
	 * Test the property 'workFlowExecutionId'
	 */
	@Test
	public void workFlowExecutionIdTest() {
		// TODO: test workFlowExecutionId
	}

	/**
	 * Test the property 'workFlowOptions'
	 */
	@Test
	public void workFlowOptionsTest() {
		// TODO: test workFlowOptions
	}

}
