/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.parodos.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.parodos.sdk.model.WorkFlowOptions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkFlowResponseDTO
 */
public class WorkFlowResponseDTOTest {
    private final WorkFlowResponseDTO model = new WorkFlowResponseDTO();

    /**
     * Model tests for WorkFlowResponseDTO
     */
    @Test
    public void testWorkFlowResponseDTO() {
        // TODO: test WorkFlowResponseDTO
    }

    /**
     * Test the property 'workFlowExecutionId'
     */
    @Test
    public void workFlowExecutionIdTest() {
        // TODO: test workFlowExecutionId
    }

    /**
     * Test the property 'workFlowOptions'
     */
    @Test
    public void workFlowOptionsTest() {
        // TODO: test workFlowOptions
    }

    /**
     * Test the property 'workStatus'
     */
    @Test
    public void workStatusTest() {
        // TODO: test workStatus
    }

}
