/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.api;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import com.google.gson.reflect.TypeToken;
import com.redhat.parodos.sdk.invoker.ApiCallback;
import com.redhat.parodos.sdk.invoker.ApiClient;
import com.redhat.parodos.sdk.invoker.ApiException;
import com.redhat.parodos.sdk.invoker.ApiResponse;
import com.redhat.parodos.sdk.invoker.Configuration;
import com.redhat.parodos.sdk.invoker.Pair;
import com.redhat.parodos.sdk.model.AccessStatusRequestDTO;
import com.redhat.parodos.sdk.model.AccessStatusResponseDTO;

public class ProjectAccessApi {

	private ApiClient localVarApiClient;

	private int localHostIndex;

	private String localCustomBaseUrl;

	public ProjectAccessApi() {
		this(Configuration.getDefaultApiClient());
	}

	public ProjectAccessApi(ApiClient apiClient) {
		this.localVarApiClient = apiClient;
	}

	public ApiClient getApiClient() {
		return localVarApiClient;
	}

	public void setApiClient(ApiClient apiClient) {
		this.localVarApiClient = apiClient;
	}

	public int getHostIndex() {
		return localHostIndex;
	}

	public void setHostIndex(int hostIndex) {
		this.localHostIndex = hostIndex;
	}

	public String getCustomBaseUrl() {
		return localCustomBaseUrl;
	}

	public void setCustomBaseUrl(String customBaseUrl) {
		this.localCustomBaseUrl = customBaseUrl;
	}

	/**
	 * Build call for getProjectAccessStatus
	 * @param id (required)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 * <table summary="Response Details" border="1">
	 * <tr>
	 * <td>Status Code</td>
	 * <td>Description</td>
	 * <td>Response Headers</td>
	 * </tr>
	 * <tr>
	 * <td>200</td>
	 * <td>Succeeded</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>400</td>
	 * <td>Bad Request</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>401</td>
	 * <td>Unauthorized</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>404</td>
	 * <td>Not found</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>409</td>
	 * <td>Conflict</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>500</td>
	 * <td>Internal Server Error</td>
	 * <td>-</td>
	 * </tr>
	 * </table>
	 */
	public okhttp3.Call getProjectAccessStatusCall(UUID id, final ApiCallback _callback) throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		}
		else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		}
		else {
			basePath = null;
		}

		Object localVarPostBody = null;

		// create path and map variables
		String localVarPath = "/api/v1/projects/access/{id}/status".replace("{" + "id" + "}",
				localVarApiClient.escapeString(id.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		final String[] localVarAccepts = { "application/json", "*/*" };
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = {};
		final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
				localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
				localVarFormParams, localVarAuthNames, _callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call getProjectAccessStatusValidateBeforeCall(UUID id, final ApiCallback _callback)
			throws ApiException {
		// verify the required parameter 'id' is set
		if (id == null) {
			throw new ApiException("Missing the required parameter 'id' when calling getProjectAccessStatus(Async)");
		}

		return getProjectAccessStatusCall(id, _callback);

	}

	/**
	 * Returns status about a specified project access request
	 * @param id (required)
	 * @return AccessStatusResponseDTO
	 * @throws ApiException If fail to call the API, e.g. server error or cannot
	 * deserialize the response body
	 * @http.response.details
	 * <table summary="Response Details" border="1">
	 * <tr>
	 * <td>Status Code</td>
	 * <td>Description</td>
	 * <td>Response Headers</td>
	 * </tr>
	 * <tr>
	 * <td>200</td>
	 * <td>Succeeded</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>400</td>
	 * <td>Bad Request</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>401</td>
	 * <td>Unauthorized</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>404</td>
	 * <td>Not found</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>409</td>
	 * <td>Conflict</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>500</td>
	 * <td>Internal Server Error</td>
	 * <td>-</td>
	 * </tr>
	 * </table>
	 */
	public AccessStatusResponseDTO getProjectAccessStatus(UUID id) throws ApiException {
		ApiResponse<AccessStatusResponseDTO> localVarResp = getProjectAccessStatusWithHttpInfo(id);
		return localVarResp.getData();
	}

	/**
	 * Returns status about a specified project access request
	 * @param id (required)
	 * @return ApiResponse&lt;AccessStatusResponseDTO&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot
	 * deserialize the response body
	 * @http.response.details
	 * <table summary="Response Details" border="1">
	 * <tr>
	 * <td>Status Code</td>
	 * <td>Description</td>
	 * <td>Response Headers</td>
	 * </tr>
	 * <tr>
	 * <td>200</td>
	 * <td>Succeeded</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>400</td>
	 * <td>Bad Request</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>401</td>
	 * <td>Unauthorized</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>404</td>
	 * <td>Not found</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>409</td>
	 * <td>Conflict</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>500</td>
	 * <td>Internal Server Error</td>
	 * <td>-</td>
	 * </tr>
	 * </table>
	 */
	public ApiResponse<AccessStatusResponseDTO> getProjectAccessStatusWithHttpInfo(UUID id) throws ApiException {
		okhttp3.Call localVarCall = getProjectAccessStatusValidateBeforeCall(id, null);
		Type localVarReturnType = new TypeToken<AccessStatusResponseDTO>() {
		}.getType();
		return localVarApiClient.execute(localVarCall, localVarReturnType);
	}

	/**
	 * Returns status about a specified project access request (asynchronously)
	 * @param id (required)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request
	 * body object
	 * @http.response.details
	 * <table summary="Response Details" border="1">
	 * <tr>
	 * <td>Status Code</td>
	 * <td>Description</td>
	 * <td>Response Headers</td>
	 * </tr>
	 * <tr>
	 * <td>200</td>
	 * <td>Succeeded</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>400</td>
	 * <td>Bad Request</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>401</td>
	 * <td>Unauthorized</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>404</td>
	 * <td>Not found</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>409</td>
	 * <td>Conflict</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>500</td>
	 * <td>Internal Server Error</td>
	 * <td>-</td>
	 * </tr>
	 * </table>
	 */
	public okhttp3.Call getProjectAccessStatusAsync(UUID id, final ApiCallback<AccessStatusResponseDTO> _callback)
			throws ApiException {

		okhttp3.Call localVarCall = getProjectAccessStatusValidateBeforeCall(id, _callback);
		Type localVarReturnType = new TypeToken<AccessStatusResponseDTO>() {
		}.getType();
		localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
		return localVarCall;
	}

	/**
	 * Build call for updateProjectAccessStatus
	 * @param id (required)
	 * @param accessStatusRequestDTO (required)
	 * @param _callback Callback for upload/download progress
	 * @return Call to execute
	 * @throws ApiException If fail to serialize the request body object
	 * @http.response.details
	 * <table summary="Response Details" border="1">
	 * <tr>
	 * <td>Status Code</td>
	 * <td>Description</td>
	 * <td>Response Headers</td>
	 * </tr>
	 * <tr>
	 * <td>204</td>
	 * <td>Updated successfully</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>400</td>
	 * <td>Bad Request</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>401</td>
	 * <td>Unauthorized</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>404</td>
	 * <td>Not found</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>409</td>
	 * <td>Conflict</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>500</td>
	 * <td>Internal Server Error</td>
	 * <td>-</td>
	 * </tr>
	 * </table>
	 */
	public okhttp3.Call updateProjectAccessStatusCall(UUID id, AccessStatusRequestDTO accessStatusRequestDTO,
			final ApiCallback _callback) throws ApiException {
		String basePath = null;
		// Operation Servers
		String[] localBasePaths = new String[] {};

		// Determine Base Path to Use
		if (localCustomBaseUrl != null) {
			basePath = localCustomBaseUrl;
		}
		else if (localBasePaths.length > 0) {
			basePath = localBasePaths[localHostIndex];
		}
		else {
			basePath = null;
		}

		Object localVarPostBody = accessStatusRequestDTO;

		// create path and map variables
		String localVarPath = "/api/v1/projects/access/{id}/status".replace("{" + "id" + "}",
				localVarApiClient.escapeString(id.toString()));

		List<Pair> localVarQueryParams = new ArrayList<Pair>();
		List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
		Map<String, String> localVarHeaderParams = new HashMap<String, String>();
		Map<String, String> localVarCookieParams = new HashMap<String, String>();
		Map<String, Object> localVarFormParams = new HashMap<String, Object>();

		final String[] localVarAccepts = { "*/*" };
		final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
		if (localVarAccept != null) {
			localVarHeaderParams.put("Accept", localVarAccept);
		}

		final String[] localVarContentTypes = { "application/json" };
		final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
		if (localVarContentType != null) {
			localVarHeaderParams.put("Content-Type", localVarContentType);
		}

		String[] localVarAuthNames = new String[] {};
		return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams,
				localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams,
				localVarFormParams, localVarAuthNames, _callback);
	}

	@SuppressWarnings("rawtypes")
	private okhttp3.Call updateProjectAccessStatusValidateBeforeCall(UUID id,
			AccessStatusRequestDTO accessStatusRequestDTO, final ApiCallback _callback) throws ApiException {
		// verify the required parameter 'id' is set
		if (id == null) {
			throw new ApiException("Missing the required parameter 'id' when calling updateProjectAccessStatus(Async)");
		}

		// verify the required parameter 'accessStatusRequestDTO' is set
		if (accessStatusRequestDTO == null) {
			throw new ApiException(
					"Missing the required parameter 'accessStatusRequestDTO' when calling updateProjectAccessStatus(Async)");
		}

		return updateProjectAccessStatusCall(id, accessStatusRequestDTO, _callback);

	}

	/**
	 * Update status of a specified project access request
	 * @param id (required)
	 * @param accessStatusRequestDTO (required)
	 * @throws ApiException If fail to call the API, e.g. server error or cannot
	 * deserialize the response body
	 * @http.response.details
	 * <table summary="Response Details" border="1">
	 * <tr>
	 * <td>Status Code</td>
	 * <td>Description</td>
	 * <td>Response Headers</td>
	 * </tr>
	 * <tr>
	 * <td>204</td>
	 * <td>Updated successfully</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>400</td>
	 * <td>Bad Request</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>401</td>
	 * <td>Unauthorized</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>404</td>
	 * <td>Not found</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>409</td>
	 * <td>Conflict</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>500</td>
	 * <td>Internal Server Error</td>
	 * <td>-</td>
	 * </tr>
	 * </table>
	 */
	public void updateProjectAccessStatus(UUID id, AccessStatusRequestDTO accessStatusRequestDTO) throws ApiException {
		updateProjectAccessStatusWithHttpInfo(id, accessStatusRequestDTO);
	}

	/**
	 * Update status of a specified project access request
	 * @param id (required)
	 * @param accessStatusRequestDTO (required)
	 * @return ApiResponse&lt;Void&gt;
	 * @throws ApiException If fail to call the API, e.g. server error or cannot
	 * deserialize the response body
	 * @http.response.details
	 * <table summary="Response Details" border="1">
	 * <tr>
	 * <td>Status Code</td>
	 * <td>Description</td>
	 * <td>Response Headers</td>
	 * </tr>
	 * <tr>
	 * <td>204</td>
	 * <td>Updated successfully</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>400</td>
	 * <td>Bad Request</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>401</td>
	 * <td>Unauthorized</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>404</td>
	 * <td>Not found</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>409</td>
	 * <td>Conflict</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>500</td>
	 * <td>Internal Server Error</td>
	 * <td>-</td>
	 * </tr>
	 * </table>
	 */
	public ApiResponse<Void> updateProjectAccessStatusWithHttpInfo(UUID id,
			AccessStatusRequestDTO accessStatusRequestDTO) throws ApiException {
		okhttp3.Call localVarCall = updateProjectAccessStatusValidateBeforeCall(id, accessStatusRequestDTO, null);
		return localVarApiClient.execute(localVarCall);
	}

	/**
	 * Update status of a specified project access request (asynchronously)
	 * @param id (required)
	 * @param accessStatusRequestDTO (required)
	 * @param _callback The callback to be executed when the API call finishes
	 * @return The request call
	 * @throws ApiException If fail to process the API call, e.g. serializing the request
	 * body object
	 * @http.response.details
	 * <table summary="Response Details" border="1">
	 * <tr>
	 * <td>Status Code</td>
	 * <td>Description</td>
	 * <td>Response Headers</td>
	 * </tr>
	 * <tr>
	 * <td>204</td>
	 * <td>Updated successfully</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>400</td>
	 * <td>Bad Request</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>401</td>
	 * <td>Unauthorized</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>404</td>
	 * <td>Not found</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>409</td>
	 * <td>Conflict</td>
	 * <td>-</td>
	 * </tr>
	 * <tr>
	 * <td>500</td>
	 * <td>Internal Server Error</td>
	 * <td>-</td>
	 * </tr>
	 * </table>
	 */
	public okhttp3.Call updateProjectAccessStatusAsync(UUID id, AccessStatusRequestDTO accessStatusRequestDTO,
			final ApiCallback<Void> _callback) throws ApiException {

		okhttp3.Call localVarCall = updateProjectAccessStatusValidateBeforeCall(id, accessStatusRequestDTO, _callback);
		localVarApiClient.executeAsync(localVarCall, _callback);
		return localVarCall;
	}

}
