/*
 * Parodos Notification Service API
 * This is the API documentation for the Parodos Notification Service. It provides operations to send out and check notification. The endpoints are secured with oAuth2/OpenID and cannot be accessed without a valid token.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.notification.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Link
 */
public class LinkTest {

	private final Link model = new Link();

	/**
	 * Model tests for Link
	 */
	@Test
	public void testLink() {
		// TODO: test Link
	}

	/**
	 * Test the property 'deprecation'
	 */
	@Test
	public void deprecationTest() {
		// TODO: test deprecation
	}

	/**
	 * Test the property 'href'
	 */
	@Test
	public void hrefTest() {
		// TODO: test href
	}

	/**
	 * Test the property 'hreflang'
	 */
	@Test
	public void hreflangTest() {
		// TODO: test hreflang
	}

	/**
	 * Test the property 'media'
	 */
	@Test
	public void mediaTest() {
		// TODO: test media
	}

	/**
	 * Test the property 'name'
	 */
	@Test
	public void nameTest() {
		// TODO: test name
	}

	/**
	 * Test the property 'profile'
	 */
	@Test
	public void profileTest() {
		// TODO: test profile
	}

	/**
	 * Test the property 'rel'
	 */
	@Test
	public void relTest() {
		// TODO: test rel
	}

	/**
	 * Test the property 'title'
	 */
	@Test
	public void titleTest() {
		// TODO: test title
	}

	/**
	 * Test the property 'type'
	 */
	@Test
	public void typeTest() {
		// TODO: test type
	}

}
