/*
 * Parodos Notification Service API
 * This is the API documentation for the Parodos Notification Service. It provides operations to send out and check notification. The endpoints are secured with oAuth2/OpenID and cannot be accessed without a valid token.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.notification.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PageMetadata
 */
public class PageMetadataTest {

	private final PageMetadata model = new PageMetadata();

	/**
	 * Model tests for PageMetadata
	 */
	@Test
	public void testPageMetadata() {
		// TODO: test PageMetadata
	}

	/**
	 * Test the property 'number'
	 */
	@Test
	public void numberTest() {
		// TODO: test number
	}

	/**
	 * Test the property 'size'
	 */
	@Test
	public void sizeTest() {
		// TODO: test size
	}

	/**
	 * Test the property 'totalElements'
	 */
	@Test
	public void totalElementsTest() {
		// TODO: test totalElements
	}

	/**
	 * Test the property 'totalPages'
	 */
	@Test
	public void totalPagesTest() {
		// TODO: test totalPages
	}

}
