/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;

/**
 * ProjectResponseDTO
 */
@lombok.Data
@lombok.AllArgsConstructor
@lombok.Builder
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProjectResponseDTO {

	public static final String SERIALIZED_NAME_CREATE_DATE = "createDate";

	@SerializedName(SERIALIZED_NAME_CREATE_DATE)
	private Date createDate;

	public static final String SERIALIZED_NAME_DESCRIPTION = "description";

	@SerializedName(SERIALIZED_NAME_DESCRIPTION)
	private String description;

	public static final String SERIALIZED_NAME_ID = "id";

	@SerializedName(SERIALIZED_NAME_ID)
	private String id;

	public static final String SERIALIZED_NAME_MODIFY_DATE = "modifyDate";

	@SerializedName(SERIALIZED_NAME_MODIFY_DATE)
	private Date modifyDate;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_USERNAME = "username";

	@SerializedName(SERIALIZED_NAME_USERNAME)
	private String username;

	public ProjectResponseDTO() {
	}

	public ProjectResponseDTO createDate(Date createDate) {

		this.createDate = createDate;
		return this;
	}

	/**
	 * Get createDate
	 * @return createDate
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public ProjectResponseDTO description(String description) {

		this.description = description;
		return this;
	}

	/**
	 * Get description
	 * @return description
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public ProjectResponseDTO id(String id) {

		this.id = id;
		return this;
	}

	/**
	 * Get id
	 * @return id
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public ProjectResponseDTO modifyDate(Date modifyDate) {

		this.modifyDate = modifyDate;
		return this;
	}

	/**
	 * Get modifyDate
	 * @return modifyDate
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public ProjectResponseDTO name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * @return name
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public ProjectResponseDTO username(String username) {

		this.username = username;
		return this;
	}

	/**
	 * Get username
	 * @return username
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ProjectResponseDTO projectResponseDTO = (ProjectResponseDTO) o;
		return Objects.equals(this.createDate, projectResponseDTO.createDate)
				&& Objects.equals(this.description, projectResponseDTO.description)
				&& Objects.equals(this.id, projectResponseDTO.id)
				&& Objects.equals(this.modifyDate, projectResponseDTO.modifyDate)
				&& Objects.equals(this.name, projectResponseDTO.name)
				&& Objects.equals(this.username, projectResponseDTO.username);
	}

	@Override
	public int hashCode() {
		return Objects.hash(createDate, description, id, modifyDate, name, username);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ProjectResponseDTO {\n");
		sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    modifyDate: ").append(toIndentedString(modifyDate)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    username: ").append(toIndentedString(username)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
