/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.model;

import java.io.IOException;
import java.util.Date;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.parodos.sdk.invoker.JSON;

/**
 * ProjectResponseDTO
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProjectResponseDTO {

	public static final String SERIALIZED_NAME_ACCESS_ROLE = "accessRole";

	@SerializedName(SERIALIZED_NAME_ACCESS_ROLE)
	private String accessRole;

	public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";

	@SerializedName(SERIALIZED_NAME_CREATED_BY)
	private String createdBy;

	public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";

	@SerializedName(SERIALIZED_NAME_CREATED_DATE)
	private Date createdDate;

	public static final String SERIALIZED_NAME_DESCRIPTION = "description";

	@SerializedName(SERIALIZED_NAME_DESCRIPTION)
	private String description;

	public static final String SERIALIZED_NAME_ID = "id";

	@SerializedName(SERIALIZED_NAME_ID)
	private UUID id;

	public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";

	@SerializedName(SERIALIZED_NAME_MODIFIED_BY)
	private String modifiedBy;

	public static final String SERIALIZED_NAME_MODIFIED_DATE = "modifiedDate";

	@SerializedName(SERIALIZED_NAME_MODIFIED_DATE)
	private Date modifiedDate;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public ProjectResponseDTO() {
	}

	public ProjectResponseDTO accessRole(String accessRole) {

		this.accessRole = accessRole;
		return this;
	}

	/**
	 * Get accessRole
	 * @return accessRole
	 **/
	@jakarta.annotation.Nullable
	public String getAccessRole() {
		return accessRole;
	}

	public void setAccessRole(String accessRole) {
		this.accessRole = accessRole;
	}

	public ProjectResponseDTO createdBy(String createdBy) {

		this.createdBy = createdBy;
		return this;
	}

	/**
	 * Get createdBy
	 * @return createdBy
	 **/
	@jakarta.annotation.Nullable
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public ProjectResponseDTO createdDate(Date createdDate) {

		this.createdDate = createdDate;
		return this;
	}

	/**
	 * Get createdDate
	 * @return createdDate
	 **/
	@jakarta.annotation.Nullable
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public ProjectResponseDTO description(String description) {

		this.description = description;
		return this;
	}

	/**
	 * Get description
	 * @return description
	 **/
	@jakarta.annotation.Nullable
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public ProjectResponseDTO id(UUID id) {

		this.id = id;
		return this;
	}

	/**
	 * Get id
	 * @return id
	 **/
	@jakarta.annotation.Nullable
	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public ProjectResponseDTO modifiedBy(String modifiedBy) {

		this.modifiedBy = modifiedBy;
		return this;
	}

	/**
	 * Get modifiedBy
	 * @return modifiedBy
	 **/
	@jakarta.annotation.Nullable
	public String getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public ProjectResponseDTO modifiedDate(Date modifiedDate) {

		this.modifiedDate = modifiedDate;
		return this;
	}

	/**
	 * Get modifiedDate
	 * @return modifiedDate
	 **/
	@jakarta.annotation.Nullable
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public ProjectResponseDTO name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * @return name
	 **/
	@jakarta.annotation.Nullable
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ProjectResponseDTO projectResponseDTO = (ProjectResponseDTO) o;
		return Objects.equals(this.accessRole, projectResponseDTO.accessRole)
				&& Objects.equals(this.createdBy, projectResponseDTO.createdBy)
				&& Objects.equals(this.createdDate, projectResponseDTO.createdDate)
				&& Objects.equals(this.description, projectResponseDTO.description)
				&& Objects.equals(this.id, projectResponseDTO.id)
				&& Objects.equals(this.modifiedBy, projectResponseDTO.modifiedBy)
				&& Objects.equals(this.modifiedDate, projectResponseDTO.modifiedDate)
				&& Objects.equals(this.name, projectResponseDTO.name);
	}

	@Override
	public int hashCode() {
		return Objects.hash(accessRole, createdBy, createdDate, description, id, modifiedBy, modifiedDate, name);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ProjectResponseDTO {\n");
		sb.append("    accessRole: ").append(toIndentedString(accessRole)).append("\n");
		sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
		sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
		sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;

	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>();
		openapiFields.add("accessRole");
		openapiFields.add("createdBy");
		openapiFields.add("createdDate");
		openapiFields.add("description");
		openapiFields.add("id");
		openapiFields.add("modifiedBy");
		openapiFields.add("modifiedDate");
		openapiFields.add("name");

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>();
	}

	/**
	 * Validates the JSON Object and throws an exception if issues found
	 * @param jsonObj JSON Object
	 * @throws IOException if the JSON Object is invalid with respect to
	 * ProjectResponseDTO
	 */
	public static void validateJsonObject(JsonObject jsonObj) throws IOException {
		if (jsonObj == null) {
			if (!ProjectResponseDTO.openapiRequiredFields.isEmpty()) { // has required
																		// fields but JSON
																		// object is null
				throw new IllegalArgumentException(String.format(
						"The required field(s) %s in ProjectResponseDTO is not found in the empty JSON string",
						ProjectResponseDTO.openapiRequiredFields.toString()));
			}
		}

		Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
		// check to see if the JSON string contains additional fields
		for (Entry<String, JsonElement> entry : entries) {
			if (!ProjectResponseDTO.openapiFields.contains(entry.getKey())) {
				throw new IllegalArgumentException(String.format(
						"The field `%s` in the JSON string is not defined in the `ProjectResponseDTO` properties. JSON: %s",
						entry.getKey(), jsonObj.toString()));
			}
		}
		if ((jsonObj.get("accessRole") != null && !jsonObj.get("accessRole").isJsonNull())
				&& !jsonObj.get("accessRole").isJsonPrimitive()) {
			throw new IllegalArgumentException(String.format(
					"Expected the field `accessRole` to be a primitive type in the JSON string but got `%s`",
					jsonObj.get("accessRole").toString()));
		}
		if ((jsonObj.get("createdBy") != null && !jsonObj.get("createdBy").isJsonNull())
				&& !jsonObj.get("createdBy").isJsonPrimitive()) {
			throw new IllegalArgumentException(String.format(
					"Expected the field `createdBy` to be a primitive type in the JSON string but got `%s`",
					jsonObj.get("createdBy").toString()));
		}
		if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull())
				&& !jsonObj.get("description").isJsonPrimitive()) {
			throw new IllegalArgumentException(String.format(
					"Expected the field `description` to be a primitive type in the JSON string but got `%s`",
					jsonObj.get("description").toString()));
		}
		if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("id").toString()));
		}
		if ((jsonObj.get("modifiedBy") != null && !jsonObj.get("modifiedBy").isJsonNull())
				&& !jsonObj.get("modifiedBy").isJsonPrimitive()) {
			throw new IllegalArgumentException(String.format(
					"Expected the field `modifiedBy` to be a primitive type in the JSON string but got `%s`",
					jsonObj.get("modifiedBy").toString()));
		}
		if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull())
				&& !jsonObj.get("name").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("name").toString()));
		}
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {

		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!ProjectResponseDTO.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'ProjectResponseDTO' and its
								// subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<ProjectResponseDTO> thisAdapter = gson.getDelegateAdapter(this,
					TypeToken.get(ProjectResponseDTO.class));

			return (TypeAdapter<T>) new TypeAdapter<ProjectResponseDTO>() {
				@Override
				public void write(JsonWriter out, ProjectResponseDTO value) throws IOException {
					JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
					elementAdapter.write(out, obj);
				}

				@Override
				public ProjectResponseDTO read(JsonReader in) throws IOException {
					JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
					validateJsonObject(jsonObj);
					return thisAdapter.fromJsonTree(jsonObj);
				}

			}.nullSafe();
		}

	}

	/**
	 * Create an instance of ProjectResponseDTO given an JSON string
	 * @param jsonString JSON string
	 * @return An instance of ProjectResponseDTO
	 * @throws IOException if the JSON string is invalid with respect to
	 * ProjectResponseDTO
	 */
	public static ProjectResponseDTO fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, ProjectResponseDTO.class);
	}

	/**
	 * Convert an instance of ProjectResponseDTO to an JSON string
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}

}
