/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WorkFlowOption
 */
@lombok.Data
@lombok.AllArgsConstructor
@lombok.Builder
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WorkFlowOption {

	public static final String SERIALIZED_NAME_DESCRIPTION = "description";

	@SerializedName(SERIALIZED_NAME_DESCRIPTION)
	private String description;

	public static final String SERIALIZED_NAME_DETAILS = "details";

	@SerializedName(SERIALIZED_NAME_DETAILS)
	private List<String> details = null;

	public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";

	@SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
	private String displayName;

	public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";

	@SerializedName(SERIALIZED_NAME_IDENTIFIER)
	private String identifier;

	public static final String SERIALIZED_NAME_WORK_FLOW_NAME = "workFlowName";

	@SerializedName(SERIALIZED_NAME_WORK_FLOW_NAME)
	private String workFlowName;

	public WorkFlowOption() {
	}

	public WorkFlowOption description(String description) {

		this.description = description;
		return this;
	}

	/**
	 * Get description
	 * @return description
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public WorkFlowOption details(List<String> details) {

		this.details = details;
		return this;
	}

	public WorkFlowOption addDetailsItem(String detailsItem) {
		if (this.details == null) {
			this.details = new ArrayList<String>();
		}
		this.details.add(detailsItem);
		return this;
	}

	/**
	 * Get details
	 * @return details
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<String> getDetails() {
		return details;
	}

	public void setDetails(List<String> details) {
		this.details = details;
	}

	public WorkFlowOption displayName(String displayName) {

		this.displayName = displayName;
		return this;
	}

	/**
	 * Get displayName
	 * @return displayName
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public WorkFlowOption identifier(String identifier) {

		this.identifier = identifier;
		return this;
	}

	/**
	 * Get identifier
	 * @return identifier
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getIdentifier() {
		return identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public WorkFlowOption workFlowName(String workFlowName) {

		this.workFlowName = workFlowName;
		return this;
	}

	/**
	 * Get workFlowName
	 * @return workFlowName
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getWorkFlowName() {
		return workFlowName;
	}

	public void setWorkFlowName(String workFlowName) {
		this.workFlowName = workFlowName;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		WorkFlowOption workFlowOption = (WorkFlowOption) o;
		return Objects.equals(this.description, workFlowOption.description)
				&& Objects.equals(this.details, workFlowOption.details)
				&& Objects.equals(this.displayName, workFlowOption.displayName)
				&& Objects.equals(this.identifier, workFlowOption.identifier)
				&& Objects.equals(this.workFlowName, workFlowOption.workFlowName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(description, details, displayName, identifier, workFlowName);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class WorkFlowOption {\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    details: ").append(toIndentedString(details)).append("\n");
		sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
		sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
		sb.append("    workFlowName: ").append(toIndentedString(workFlowName)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
