/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.redhat.parodos.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.parodos.sdk.model.ArgumentRequestDTO;
import com.redhat.parodos.sdk.model.WorkRequestDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WorkFlowRequestDTO
 */
@lombok.Data @lombok.AllArgsConstructor @lombok.Builder
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WorkFlowRequestDTO {
  public static final String SERIALIZED_NAME_ARGUMENTS = "arguments";
  @SerializedName(SERIALIZED_NAME_ARGUMENTS)
  private List<ArgumentRequestDTO> arguments = null;

  public static final String SERIALIZED_NAME_PROJECT_ID = "projectId";
  @SerializedName(SERIALIZED_NAME_PROJECT_ID)
  private String projectId;

  public static final String SERIALIZED_NAME_WORK_FLOW_NAME = "workFlowName";
  @SerializedName(SERIALIZED_NAME_WORK_FLOW_NAME)
  private String workFlowName;

  public static final String SERIALIZED_NAME_WORKS = "works";
  @SerializedName(SERIALIZED_NAME_WORKS)
  private List<WorkRequestDTO> works = null;

  public WorkFlowRequestDTO() { 
  }

  public WorkFlowRequestDTO arguments(List<ArgumentRequestDTO> arguments) {
    
    this.arguments = arguments;
    return this;
  }

  public WorkFlowRequestDTO addArgumentsItem(ArgumentRequestDTO argumentsItem) {
    if (this.arguments == null) {
      this.arguments = new ArrayList<ArgumentRequestDTO>();
    }
    this.arguments.add(argumentsItem);
    return this;
  }

   /**
   * Get arguments
   * @return arguments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ArgumentRequestDTO> getArguments() {
    return arguments;
  }


  public void setArguments(List<ArgumentRequestDTO> arguments) {
    this.arguments = arguments;
  }


  public WorkFlowRequestDTO projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProjectId() {
    return projectId;
  }


  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public WorkFlowRequestDTO workFlowName(String workFlowName) {
    
    this.workFlowName = workFlowName;
    return this;
  }

   /**
   * Get workFlowName
   * @return workFlowName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getWorkFlowName() {
    return workFlowName;
  }


  public void setWorkFlowName(String workFlowName) {
    this.workFlowName = workFlowName;
  }


  public WorkFlowRequestDTO works(List<WorkRequestDTO> works) {
    
    this.works = works;
    return this;
  }

  public WorkFlowRequestDTO addWorksItem(WorkRequestDTO worksItem) {
    if (this.works == null) {
      this.works = new ArrayList<WorkRequestDTO>();
    }
    this.works.add(worksItem);
    return this;
  }

   /**
   * Get works
   * @return works
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WorkRequestDTO> getWorks() {
    return works;
  }


  public void setWorks(List<WorkRequestDTO> works) {
    this.works = works;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkFlowRequestDTO workFlowRequestDTO = (WorkFlowRequestDTO) o;
    return Objects.equals(this.arguments, workFlowRequestDTO.arguments) &&
        Objects.equals(this.projectId, workFlowRequestDTO.projectId) &&
        Objects.equals(this.workFlowName, workFlowRequestDTO.workFlowName) &&
        Objects.equals(this.works, workFlowRequestDTO.works);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arguments, projectId, workFlowName, works);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkFlowRequestDTO {\n");
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    workFlowName: ").append(toIndentedString(workFlowName)).append("\n");
    sb.append("    works: ").append(toIndentedString(works)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

