/*
 * Parodos Workflow Service API
 * This is the API documentation for the Parodos Workflow Service. It provides operations to execute assessments to determine infrastructure options (tooling + environments). Also executes infrastructure task workflows to call downstream systems to stand-up an infrastructure option.
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.redhat.parodos.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WorkParameterValueRequestDTO
 */
@lombok.Data
@lombok.AllArgsConstructor
@lombok.Builder
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WorkParameterValueRequestDTO {

	public static final String SERIALIZED_NAME_KEY = "key";

	@SerializedName(SERIALIZED_NAME_KEY)
	private String key;

	public static final String SERIALIZED_NAME_VALUE = "value";

	@SerializedName(SERIALIZED_NAME_VALUE)
	private String value;

	public static final String SERIALIZED_NAME_WORK_NAME = "workName";

	@SerializedName(SERIALIZED_NAME_WORK_NAME)
	private String workName;

	public WorkParameterValueRequestDTO() {
	}

	public WorkParameterValueRequestDTO key(String key) {

		this.key = key;
		return this;
	}

	/**
	 * Get key
	 * @return key
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public WorkParameterValueRequestDTO value(String value) {

		this.value = value;
		return this;
	}

	/**
	 * Get value
	 * @return value
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public WorkParameterValueRequestDTO workName(String workName) {

		this.workName = workName;
		return this;
	}

	/**
	 * Get workName
	 * @return workName
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getWorkName() {
		return workName;
	}

	public void setWorkName(String workName) {
		this.workName = workName;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		WorkParameterValueRequestDTO workParameterValueRequestDTO = (WorkParameterValueRequestDTO) o;
		return Objects.equals(this.key, workParameterValueRequestDTO.key)
				&& Objects.equals(this.value, workParameterValueRequestDTO.value)
				&& Objects.equals(this.workName, workParameterValueRequestDTO.workName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(key, value, workName);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class WorkParameterValueRequestDTO {\n");
		sb.append("    key: ").append(toIndentedString(key)).append("\n");
		sb.append("    value: ").append(toIndentedString(value)).append("\n");
		sb.append("    workName: ").append(toIndentedString(workName)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
